kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: granite-instruct
data:
  uwl_metrics_list.yaml: |
    matches:
      - __name__=~"(llm_performance_.*)"
      - __name__=~"(vllm:.*)"
