apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-load-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
