apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: llm-load-test-exporter
  name: llm-load-test-exporter
  namespace: granite-instruct
spec:
  endpoints:
  - interval: 120s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: llm-load-test-exporter
